### ISSUE TITLE
doesn't work in the browser

### ISSUE THREAD

**Issue by nickperkinslondon** [thenativeweb/measure-time#1]
doesn't work in the browser
(process.hrtime is not a function)
..which is ok, but I wish I knew that before trying to use it with webpack

**Comment by goloroden** [comment]
First of all, I'm very sorry for this 😢

Actually we have never tried to run it in the browser, because we only needed it for the backend. A quick Google search has lead me to [browser-process-hrtime](https://www.npmjs.com/package/browser-process-hrtime), which acts as a shim that also works within the browser, so it could be pretty easy to come up with a version that works with Node.js *and* the browser.

Could you imagine to create a PR for this?

**Comment by nickperkinslondon** [comment]
no problem -- a lot of timing packages don't seem to support the browser
I ended up just using "performance.now()"
